
export const alumni = [
      {
        id: 1,
        name: "Aarti Kumari",
        designation: "Joined in 2022",
        imageUrl: "/images/team/alumni/Aarti_Kumari.jpg",
        bio: "Currently pursuing B.Tech in Computer Science at BRCM College of Engineering and Technology",
        linkedin:"https://www.linkedin.com/in/aarti-kumari-a5898b327/",
      },
      {
        id: 2,
        name: "Aashi Kumari",
        designation: "Joined in 2021",
        imageUrl: "/images/team/alumni/Aashi_Kumari.jpg",
        bio: "Currently pursuing B.Tech in Computer Science with a specialization in Cyber Security at Darbhanga College of Engineering",
        linkedin: "https://www.linkedin.com/in/aashi-kumari-0a24a1307/"
      },
      {
        id: 3,
        name: "Aashutosh Kumar Sharma",
        designation: "Joined in 2021",
        imageUrl: "/images/team/alumni/Aashutosh_Kumar_Sharma.jpg",
        bio: "Currently pursuing B.Tech in Mechanical Engineering at Malaviya National Institute of Technology, Jaipur",
        linkedin: "https://www.linkedin.com/in/aashutosh-kumar-sharma-508309293"
      },
      {
        id: 4,
        name: "Abhay Raj",
        designation: "Joined in 2021",
        imageUrl: "/images/team/alumni/Abhay_Raj.jpg",
        bio: "Currently pursuing B.Tech in Computer Science at Scaler School of Technology",
        linkedin:"https://www.linkedin.com/in/abhay-raj-ab0445287"
      },
      {
        id: 5,
        name: "Abhiyanka Kumari",
        designation: "Joined in 2020",
        imageUrl: "/images/team/alumni/Abhiyanka_kumari.jpg",
        bio: "Currently pursuing B.Tech in Computer Science at Techno Main Salt Lake",
        linkedin: "https://www.linkedin.com/in/abhiyanka-kumari-26b96b291"
      },
      {
        id: 6,
        name: "Akriti Anchal",
        designation: "Joined in 2021",
        imageUrl: "/images/team/alumni/Akriti_Aanchal.jpg",
        bio: "Currently pursuing B.Tech in Information Technology at Chandigarh Engineering College",
        linkedin:"https://www.linkedin.com/in/akriti-anchal-258526291"
      },
      {
        id: 7,
        name: "Akshay Kumar",
        designation: "Joined in 2022",
        imageUrl: "/images/team/alumni/Akshay_Kumar.jpeg",
        bio: "Currently pursuing B.Tech in Information Technology at Netaji Subhash Engineering College",
        linkedin:"https://www.linkedin.com/in/akshay-kumar-462938291"
      },
      {
        id: 8,
        name: "Alisha Patel",
        designation: "Joined in 2022",
        imageUrl: "/images/team/alumni/Alisha_Patel.jpg",
        bio: "Currently pursuing B.Tech in Information Technology at Netaji Subhash Engineering College",
        linkedin:"http://www.linkedin.com/in/alisha-patel-658702253"
      },
      {
        id: 9,
        name: "Alok Kumar",
        designation: "Joined in 2022",
        imageUrl: "/images/team/alumni/Alok_Kumar.jpg",
        bio: "Currently pursuing B.Tech in Chemical Engineering at Indian Institute of Technology (BHU)",
        linkedin: "https://www.linkedin.com/in/alok-kumar-11a11228a?trk=contact-info"
      },
      {
        id: 10,
        name: "Amar Kumar",
        designation: "Joined in 2020",
        imageUrl: "/images/team/alumni/Amar_Kumar.jpg",
        bio: "Currently pursuing B.Tech in Computer Science at Netaji Gaya College of Engineering",
        linkedin: "https://www.linkedin.com/in/amar-kumar-88183b292?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: 11,
        name: "Amish Manjul",
        designation: "Joined in 2017",
        imageUrl: "/images/team/alumni/Amish_Manjul.jpg",
        bio: "Currently pursuing B.Tech in Computer Science with a specilization in AI/ML at Institue of Engineering and Management",
        linkedin: "https://www.linkedin.com/in/amish-manjul-95851425a",
      },
      {
        id: 12,
        name: "Amisha Kumari",
        designation: "Joined in 2022",
        imageUrl: "/images/team/alumni/Amisha_Kumari.jpg",
        bio: "Currently pursuing B.Tech in Computer Science at BP Poddar Institute of Mangament and Technology",
        linkedin:"https://www.linkedin.com/in/amisha-kumari-261256326?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: 13,
        name: "Amit Kumar",
        designation: "Joined in 2021",
        imageUrl: "/images/team/alumni/Amit_Kumar.jpg",
        bio: "Currently pursuing B.Tech in Computer Science at Motilal Nehru National Institute of Technology (MNNIT), Allahabad",
        linkedin: "https://www.linkedin.com/in/amit-kumar-3a4137256/",
      },
      {
        id: 14,
        name: "Amit Kumar",
        designation: "Joined in 2021",
        imageUrl: "/images/team/alumni/Amit_Kumar1.jpg",
        bio: "Currently pursuing B.Tech in Information Technology at Indian Institute of Information Technology, Allahabad",
        linkedin:"https://www.linkedin.com/in/amit-kumar-442953234?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: 15,
        name: "Amit Kumar",
        designation: "Joined in 2021",
        imageUrl: "/images/team/alumni/Amit_Kumar2.jpg",
        bio: "Currently pursuing B.Tech in Information Technology at B.P. Poddar Institute of Management and Technology",
        linkedin: "https://www.linkedin.com/in/amit-kumar-4a6279291"
      },
      {
        id: 16,
        name: "Anand Kishor",
        designation: "Joined in 2022",
        imageUrl: "/images/team/alumni/Anand_Kishor.jpg",
        bio: "Currently pursuing B.Tech in Computer Science at Techno Main Salt Lake",
        linkedin: "https://www.linkedin.com/in/anand-kishor-369a00323",
      },
      {
        id: 17,
        name: "Ananya Kumari",
        designation: "Joined in 2022",
        imageUrl: "/images/team/alumni/Ananya_Kumari.jpg",
        bio: "Currently pursuing B.Tech in Computer Science at B.P. Poddar Institute of Management and Technology",
        linkedin: "https://www.linkedin.com/in/ananya-kumari-227838326?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        },
      {
        id: 18,
        name: "Anjali Kumari",
        designation: "Joined in 2020",
        imageUrl: "/images/team/alumni/Anjali _Kumari.jpg",
        bio: "Currently pursuing B.Tech in Information Technology at Chandigarh Engineering College",
        linkedin: "https://www.linkedin.com/in/anjali-kumari-315001292",
      },
      {
        id: 20,
        name: "Anjali Kumari",
        designation: "Joined in 2021",
        imageUrl: "/images/team/alumni/Anjali_Kumari1.jpg",
        bio: "Currently pursuing Bachelor of Computer Applications",
      },
      {
        id: 21,
        name: "Anjali Kumari",
        designation: "Joined in 2022",
        imageUrl: "/images/team/alumni/Anjali_Kumari2.jpeg",
        bio: "Currently pursuing B.Tech in Information Technology at Dr. B.C Roy Engineering College, Durgapur",
        linkedin:"https://www.linkedin.com/in/anjali-kumari-40b158326?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: 22,
        name: "Ankit Raj",
        designation: "Joined in 2021",
        imageUrl: "/images/team/alumni/Ankit_Raj.jpg",
        bio: "Currently pursuing B.Tech in Computer Science at Indian Institute of Information Technology, Guwahati",
        linkedin: "https://www.linkedin.com/in/ankit-raj-bb938b242/", 
      },
      {
        id: 24,
        name: "Anuradha Kumari",
        designation: "Joined in 2021",
        imageUrl: "/images/team/alumni/Anuradha_Kumari.jpg",
        bio: "Currently pursuing B.Tech in Information Technology at B.P. Poddar Institute of Management and Technology",
        linkedin: "https://www.linkedin.com/in/anuradha-kumari-b00b52291",
      },
      {
        id: 25,
        name: "Anushka",
        designation: "Joined in 2020",
        imageUrl: "/images/team/alumni/Anushka.jpg",
        bio: "Currently pursuing B.Tech in Information Technology",
        linkedin: "https://www.linkedin.com/in/anushka-%E0%A4%85-731154326?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: 26,
        name: "Archana Kumari",
        designation: "Joined in 2020",
        imageUrl: "/images/team/alumni/Archana_Kumari.jpg",
        bio: "Currently pursuing B.Tech in Electronics and Communication Engineering at National Institute of Technology, Patna ",
        linkedin: "https://www.linkedin.com/in/archana-kumari-bb9b93258",
      },
      {
        id: 27,
        name: "Arti Kumari",
        designation: "Joined in 2022",
        imageUrl: "/images/team/alumni/Arti_Kumari.jpg",
        bio: "Currently pursuing B.Tech in Civil Engineering at Indian Institute of Engineering Science and Technology, Shibpur",
        linkedin: "https://www.linkedin.com/in/arti-kumari-886645326?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: 28,
        name: "Aryan Sharma",
        designation: "Joined in 2023",
        imageUrl: "/images/team/alumni/Aryan_Sharma.jpg",
        bio: "Currently pursuing B.Tech in Computer Science at Joy University",
        linkedin: "https://www.linkedin.com/in/aryan-sharma-710a06326?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: 29,
        name: "Ashish Anand",
        designation: "Joined in 2022",
        imageUrl: "/images/team/alumni/Ashish_Anand.jpg",
        bio: "Currently pursuing B.Tech in Metallurgical and Material Engineering at National Institute of Technology, Jamshedpur",
        linkedin: "https://www.linkedin.com/in/ashish-anand-bb89b028a?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: 30,
        name: "Ashish Kumar",
        designation: "Joined in 2017",
        imageUrl: "/images/team/alumni/Ashish_Kumar.JPG",
        bio: "Currently pursuing B.Tech in Computer Science at Bengal College of Engineering and Technology",
        linkedin: "https://www.linkedin.com/in/ashish-kumar-58895a290",
      },
      {
        id: 31,
        name: "Avin Kumar",
        designation: "Joined in 2020",
        imageUrl: "/images/team/alumni/Avin.jpg",
        bio: "Currently pursuing B.Tech in Computer Science at Chandigarh University",
        linkedin: "https://www.linkedin.com/in/avin-kumar-76906024b/",
      },
      {
        id: 32,
        name: "Avinash Kumar",
        designation: "Joined in 2021",
        imageUrl: "/images/team/alumni/Avinash_Kumar.jpg",
        bio: "Currently pursuing B.Tech in Mechanical Engineering at Indian Institute of Technology, Jodhpur",
        linkedin: "http://linkedin.com/in/avinash-kumar-66175a295",
      },
      {
        id: 33,
        name: "Chandani Kumari",
        designation: "Joined in 2021",
        imageUrl: "/images/team/alumni/Chandani_Kumari.jpg",
        bio: "Currently pursuing Bachelor of Computer Applications at DPG Degree College, Haryana",
      },
      {
        id: 34,
        name: "Dabloo Kumar",
        designation: "Joined in 2021",
        imageUrl: "/images/team/alumni/Dabloo_Kumar.jpg",
        bio: "Currently pursuing B.Tech in Information Technology at Chandigarh Engineering College ",
        linkedin: "https://www.linkedin.com/in/dabloo-kumar-3519a7292?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: 35,
        name: "Deepak Kumar",
        designation: "Joined in 2024",
        imageUrl: "/images/team/alumni/Deepak_Kumar.jpg",
        bio: "Currently pursuing B.Tech in Computer Science at Jaypee Institute of Information Technology, Noida",
      },
      {
        id: 36,
        name: "Deepali Kumari",
        designation: "Joined in 2022",
        imageUrl: "/images/team/alumni/Deepali_Kumari.jpg",
        bio: "Currently pursuing B.Tech in Computer Science at GEC SHEIKHPURA",
        linkdin: "https://www.linkedin.com/in/deepali-kumari-23b283325?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: 37,
        name: "Dhiraj Kumar",
        designation: "Joined in 2023",
        imageUrl: "/images/team/alumni/Dhiraj_Kumar.jpg",
        bio: "Currently pursuing B.Tech in Computer Science at Haldia Institute of Technology ",
        linkedin: "https://www.linkedin.com/in/dhiraj-kumar-b54681326?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: 38,
        name: "Geetanjali Kumari",
        designation: "Joined in 2021",
        imageUrl: "/images/team/alumni/Geetanjali_Kumari.jpg",
        bio: "Currently pursuing B.Tech in Metallurgical and Material Engineering at Malaviya National Institute of Technology, Jaipur",
        linkedin: "https://www.linkedin.com/in/geetanjali-kumari-789b6a292",
      },
      {
        id: 39,
        name: "Guddu Kumar",
        designation: "Joined in 2019",
        imageUrl: "/images/team/alumni/Guddu_Kumar.JPG",
        bio: "Currently pursuing B.Tech in Computer Science at NIST Institute Of Science And Technology,Berhampur",
        linkedin: "https://www.linkedin.com/in/guddu-kumar-3b3660247/",
      },
      {
        id: 40,
        name: "Gulshan Kumar",
        designation: "Joined in 2023",
        imageUrl: "/images/team/alumni/Gulshan_Kumar.jpg",
        bio: "Currently pursuing  B.Tech in Metallurgy and Materials Engineering at National Institute of Technology, Rourkela",
        linkedin: "https://www.linkedin.com/in/gulshan-kumar-0a73b8291",
      },
      {
        id: 41,
        name: "Harsh Kumar",
        designation: "Joined in 2022",
        imageUrl: "/images/team/alumni/Harsh_Kumar.jpg",
        bio: "Currently pursuing B.Tech in Metallurgy and Materials Engineering at National Institute of Technology, Trichy",
        linkedin: "https://www.linkedin.com/in/harsh-kumar-743839292?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: 42,
        name: "Harsh Ranjan",
        designation: "Joined in 2021",
        imageUrl: "/images/team/alumni/Harsh_Ranjan.jpg",
        bio: "Currently pursuing B.Tech in Computer Science at BRCM College of Engineering and Technology",
        linkedin:"https://www.linkedin.com/in/harsh-ranjan-2a8676325?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: 43,
        name: "Hemant Kumar",
        designation: "Joined in 2018",
        imageUrl: "/images/team/alumni/Hemant_Kumar.jpg",
        bio: "Currently pursuing B.Tech in Metallurgy and Materials Engineering at Visvesvaraya National Institute of Technology ",
        linkedin: "https://www.linkedin.com/in/hemant-kumar-390133290",
      },
      {
        id: 44,
        name: "Hritik Kumar",
        designation: "Joined in 2020",
        imageUrl: "/images/team/alumni/Hritik_Kumar.jpg",
        bio: "Currently pursuing B.Tech in Computer Science with a specilization in AI/ML Techno Main Saltlake, Kolkata",
        linkedin: "https://www.linkedin.com/in/hritikkumarpd",
      },
      {
        id: 45,
        name: "Indradev Kumar",
        designation: "Joined in 2015",
        imageUrl: "/images/team/alumni/Indradev_Kumar.jpg",
        bio: "Currently pursuing B.Tech in Mining at National Institute of Technology, Rourkela ",
        linkedin: "https://www.linkedin.com/in/indradev-kumar-014712292?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: 46,
        name: "Kareena Kumari",
        designation: "Joined in 2020",
        imageUrl: "/images/team/alumni/Kareena_Kumari.jpg",
        bio: "Currently pursuing B.Tech in Metallurgical Engineering at Indian Institute of Technology (BHU)",
        linkedin: "https://www.linkedin.com/in/kareena-kumari-711497271",
      },
      {
        id: 47,
        name: "Kashish Kumari",
        designation: "Joined in 2020",
        imageUrl: "/images/team/alumni/Kashish_Kumari.jpg",
        bio: "Currently pursuing B.Tech in Production Engineering at National Institute of Technology, Trichy",
        linkedin: "https://www.linkedin.com/in/kashish-kumari-391845326?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: 48,
        name: "Kemi Kumari",
        designation: "Joined in 2022",
        imageUrl: "/images/team/alumni/Kemi_Kumari.jpg",
        bio: "Currently pursuing B.Tech in Electrical and Electronics Engineering at Gaya College of Engineering ",
        linkedin: "https://www.linkedin.com/in/kemi-kumari-216515325?utm_source=share&utm_campaign=shhttps://www.linkedin.com/in/kemi-kumari-216515325?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_appare_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: 49,
        name: "Keshar Kumar",
        designation: "Joined in 2022",
        imageUrl: "/images/team/alumni/Keshar_Kumar.jpg",
        bio: "Currently pursuing B.Tech in Information Technology at Chandigarh Group of College",
        linkedin: "https://www.linkedin.com/in/keshar-kumar-3355b1293",
      },
      {
        id: 50,
        name: "Khushi Kumari",
        designation: "Joined in 2022",
        imageUrl: "/images/team/alumni/Khushi_Kumari.jpg",
        bio: "Currently pursuing B.Tech in Civil Engineering at Indian Institute of Technology (BHU)",
        linkedin: "https://www.linkedin.com/in/khushi-kumari-ab7a342a4?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: 51,
        name: "Khushi Kumari",
        designation: "Joined in 2022",
        imageUrl: "/images/team/alumni/Khushi_Kumari1.jpg",
        bio: "Currently pursuing B.Tech in Electronics and Communication Engineering at BCE Bhagalpur Engineering College ",
      },
      {
        id: 52,
        name: "Khushi Nath",
        designation: "Joined in 2021",
        imageUrl: "/images/team/alumni/Khushi_Nath.jpg",
        bio: "Currently pursuing B.Tech in Computer Science at Chandigarh Group of College",
        linkedin: "https://www.linkedin.com/in/khushi-nath-9a443533a?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: 53,
        name: "Khushi Raj",
        designation: "Joined in 2022",
        imageUrl: "/images/team/alumni/Khushi_Raj.jpg",
        bio: "Currently pursuing B.Tech in Computer Science at Netaji Subhash Engineering College ",
      },
      {
        id: 54,
        name: "Kusum Kumari",
        designation: "Joined in 2020",
        imageUrl: "/images/team/alumni/Kusum_Kumari.jpg",
        bio: "Currently pursuing B.Tech in Computer Science at BP Poddar Institute of Mangament and Technology",
        linkedin: "https://www.linkedin.com/in/kusum-kumari-153957291",
      },
      {
        id: 55,
        name: "Kusum Kumari",
        designation: "Joined in 2021",
        imageUrl: "/images/team/alumni/Kusum_Kumari1.jpg",
        bio: "Currently pursuing Bachelor in Computer Applications at Mirza Ghalib College,Gaya",
      },
      {
        id: 56,
        name: "Madhu Kumari",
        designation: "Joined in 2021",
        imageUrl: "/images/team/alumni/Madhu_Kumari.jpg",
        bio: "Currently pursuing B.Tech in Computer Science at National Instiute of Technology, Patna",
        linkedin: "https://www.linkedin.com/in/madhu-kumari-5a5a36293/",
      },
      {
        id: 57,
        name: "Manish Kumar",
        designation: "Joined in 2023",
        imageUrl: "/images/team/alumni/Manish_Kumar.jpg",
        bio: "Currently pursuing B.Tech in Computer Science at  National Instiute of Technology, Warangal",
        linkedin: "https://in.linkedin.com/in/manish-choudhary-55b52026a",
        },
      {
        id: 58,
        name: "Manish Kumar",
        designation: "Joined in 2023",
        imageUrl: "/images/team/alumni/Manish_Kumar1.png",
        bio: "Currently pursuing B.Tech in Civil Engineering at National Instiute of Technology, Calicut",
        linkedin: "https://www.linkedin.com/in/manish-rajput-676599327?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: 59,
        name: "Meghnath Kumar",
        designation: "Joined in 2021",
        imageUrl: "/images/team/alumni/Meghnath_Kumar.jpg",
        bio: "Currently pursuing B.Tech in Information Technology at Chandigarh Engineering College",
      },
      {
        id: 60,
        name: "Neha Kumari",
        designation: "Joined in 2021",
        imageUrl: "/images/team/alumni/Neha_Kumari.jpg",
        bio: "Currently pursuing B.Tech in Civil Engineering at Indian Institute of Engineering Science and Technology, Shibpur",
        linkedin:"https://www.linkedin.com/in/neha-kumari-077152326?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: 61,
        name: "Neha Kumari",
        designation: "Joined in 2022",
        imageUrl: "/images/team/alumni/Neha_Kumari1.jpg",
        bio: "Currently pursuing B.Tech in Information Technology at BP Poddar Institute of Mangament and Technology",
        linkedin: "https://www.linkedin.com/in/neha-kumari-3a0256326?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: 62,
        name: "Nisha Kumari",
        designation: "Joined in 2022",
        imageUrl: "/images/team/alumni/Nisha_Kumari.jpg",
        bio: "Currently pursuing B.Tech in Computer Science at BP Poddar Institute of Mangament and Technology",
        linkedin:"https://www.linkedin.com/in/nisha-kumari-215153326?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app", 
      },
      {
        id: 63,
        name: "Nitish Kumar",
        designation: "Joined in 2022",
        imageUrl: "/images/team/alumni/Nitish_Kumar.jpg",
        bio: "Currently pursuing B.Tech in Mining at Indian Institute of Technology (BHU)",
        linkedin: "https://www.linkedin.com/in/nitish-kumar-40099a285?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: 64,
        name: "Pinki Kumari",
        designation: "Joined in 2021",
        imageUrl: "/images/team/alumni/Pinki_Kumari.jpg",
        bio: "Currently pursuing B.Tech in Computer Science at L.N.J.P.I.T. Engineering Chapra",
        linkedin: "https://www.linkedin.com/in/nitish-kumar-40099a285?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: 65,
        name: "Prashant Kumar",
        designation: "Joined in 2020",
        imageUrl: "/images/team/alumni/Prashant_Kumar.jpg",
        bio: "Currently pursuing B.Tech in Electrical and Electronics Engineering at National Institute of Technology, Andhra Pradesh",
        linkedin: "https://www.linkedin.com/in/prashant-kumar-124a64291",
      },
      {
        id: 66,
        name: "Prem Ranjan",
        designation: "Joined in 2018",
        imageUrl: "/images/team/alumni/Prem_Ranjan.jpg",
        bio: "Currently pursuing B.Tech in Computer Science at Maulana Abul Kalam Azad University of Technology",
        linkedin: "https://www.linkedin.com/in/prem-ranjan-92903927a",
      },
      {
        id: 67,
        name: "Prity Kumari",
        designation: "Joined in 2021",
        imageUrl: "/images/team/alumni/Prity_Kumari.jpg",
        bio: "Currently pursuing B.Tech in Metallurgy and Materials Engineering at Visvesvaraya National Institute of Technology",
        linkedin: "https://www.linkedin.com/in/prity-kumari-6242942ba",
      },
      {
        id: 68,
        name: "Priyanshi Kumari",
        designation: "Joined in 2022",
        imageUrl: "/images/team/alumni/Priyanshi_Kumari.jpg",
        bio: "Currently pursuing Bachelor of Information Technology at St.Thomas Collage of Engineering and Technology",
      },
      {
        id: 69,
        name: "Priyanshu Kumar",
        designation: "Joined in 2022",
        imageUrl: "/images/team/alumni/Priyanshu_Kumar.jpg",
        bio: "Currently pursuing B.Tech in Metallurgy at National Institute of Advanced Manufacturing Technology, Ranchi",
        linkedin: "https://www.linkedin.com/in/priyanshu-kumar-a16315328?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: 70,
        name: "Puja Kumari",
        designation: "Joined in 2021",
        imageUrl: "/images/team/alumni/Puja_Kumari.JPG",
        bio: "Currently pursuing B.Tech in Information Technology at Techno International New Town Kolkata (West Bengal) ",
        linkedin: "https://www.linkedin.com/in/puja-kumari-ba0583292",
      },
      {
        id: 71,
        name: "Puja Kumari",
        designation: "Joined in 2018",
        imageUrl: "/images/team/alumni/Puja_Kumari1.jpg",
        bio: "Currently pursuing B.Tech in Computer Science with specialization in AI/ML at B.P. Mandal College of Engineering, Madhepura",
      },
      {
        id: 72,
        name: "Rachit Kumar",
        designation: "Joined in 2020",
        imageUrl: "/images/team/alumni/Rachit_Kumar.png",
        bio: "Currently pursuing B.Tech in Computer Science at Chandigarh Engineering College",
        linkedin: "https://www.linkedin.com/in/rachit-kumar-424382263?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",  
      },
      {
        id: 73,
        name: "Rahul Chand",
        designation: "Joined in 2021",
        imageUrl: "/images/team/alumni/Rahul_Chand.JPG",
        bio: "Currently pursuing B.Tech in Information Technology at Chandigarh Engineering College",
        linkedin: "https://www.linkedin.com/in/rahul-chand-0326b02a9?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: 74,
        name: "Rahul Kumar",
        designation: "Joined in 2023",
        imageUrl: "/images/team/alumni/Rahul_Kumar.jpg",
        bio: "Currently pursuing B.Tech in Information Technology at Netaji Subhash Engineering College",
        linkedin: "https://www.linkedin.com/in/rahul-kumar-391113286",
      },
      {
        id: 75,
        name: "Rahul Kumar",
        designation: "Joined in 2021",
        imageUrl: "/images/team/alumni/Rahul_Kumar1.jpg",
        bio: "Currently pursuing B.Tech in Information Technology at BP Poddar Institute of Mangament and Technology",
        linkedin: "https://www.linkedin.com/in/rahul-kumar-582833291",
      },
      {
        id: 76,
        name: "Rakhi Kumari",
        designation: "Joined in 2017",
        imageUrl: "/images/team/alumni/Rakhi_Kumari.jpg",
        bio: "Currently pursuing B.Tech in Computer Science at National Institute of Technology, Kurukshetra",
        linkedin:"https://www.linkedin.com/in/rakhi-kumari-99b918290",
      },
      {
        id: 77,
        name: "Rakhi Kumari",
        designation: "Joined in 2022",
        imageUrl: "/images/team/alumni/Rakhi_Kumari1.jpg",
        bio: "Currently pursuing B.Tech in Computer Science at Netaji Subhash Engineering College ",
      },
      {
        id: 78,
        name: "Rakhi Kumari",
        designation: "Joined in 2023",
        imageUrl: "/images/team/alumni/Rakhi_Kumari2.jpg",
        bio: "Currently pursuing B.Tech in Computer Science at BRCM College of Engineering and Technology",
        linkedin: "https://www.linkedin.com/in/rakhi-kumari-3346ab326?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: 79,
        name: "Ram Ratan",
        designation: "Joined in 2020",
        imageUrl: "/images/team/alumni/Ram_Ratan.jpg",
        bio: "Currently pursuing B.Tech in B.Tech in Electronics and Communication Engineering at Indian Institute of Space Science and Technology",
        linkedin: "https://www.linkedin.com/in/ram-ratan-7840aa266",
      },
      {
        id: 80,
        name: "Ravi Kumar",
        designation: "Joined in 2021",
        imageUrl: "/images/team/alumni/Ravi_Kumar.jpg",
        bio: "Currently pursuing B.Tech in Computer Science at National Institute of Technology, Patna",
        linkedin: "https://www.linkedin.com/in/ravi-kumar-520910257",
      },
      {
        id: 81,
        name: "Ravi Kumar",
        designation: "Joined in 2018",
        imageUrl: "/images/team/alumni/Ravi_Kumar.png",
        bio: "Currently pursuing B.Tech in Computer Science at Chandigarh Engineering College",
        linkedin: "http://www.linkedin.com/in/ravi-kumar-921577260",
      },
      {
        id: 82,
        name: "Rohit Kumar",
        designation: "Joined in 2021",
        imageUrl: "/images/team/alumni/Rohit_Kumar.jpg",
        bio: "Currently pursuing B.Tech in Computer Science at Chandigarh Engineering College",
        linkedin: "http://www.linkedin.com/in/rohit-kumar-8b721a255",
      },
      {
        id: 83,
        name: "Rohini Kumari",
        designation: "Joined in 2022",
        imageUrl: "/images/team/alumni/Rohni_Kumari.jpg",
        bio: "Currently pursuing B.Tech in Computer Science at Netaji Subhash Engineering College ",
      },
      {
        id: 84,
        name: "Rupam Kumar",
        designation: "Joined in 2019",
        imageUrl: "/images/team/alumni/Rupam_Kumar.jpg",
        bio: "Currently pursuing B.Tech in Mechanical Engineering at National Institute of Technology, Durgapur",
        linkedin: "https://www.linkedin.com/in/rupam-kumar-86a999254",
      },
      {
        id: 85,
        name: "Sachin Kumar",
        designation: "Joined in 2021",
        imageUrl: "/images/team/alumni/Sachin_Kumar.jpg",
        bio: "Currently pursuing B.Tech in Computer Science with specialization in Data Science at Chandigarh Engineering College",
        linkedin: "https://www.linkedin.com/in/sachin-kumar-a889a9292",
      },
      {
        id: 86,
        name: "Sahul Kumar",
        designation: "Joined in 2020",
        imageUrl: "/images/team/alumni/Sahul_Kumar.jpeg",
        bio: "Currently pursuing B.Tech in Information Technology at Indian Institute of Information Technology, Allahabad",
        linkedin: "https://www.linkedin.com/in/sahul-kumar-1028bb282/",
      },
      {
        id: 87,
        name: "Sahul Nath",
        designation: "Joined in 2017",
        imageUrl: "/images/team/alumni/Sahul_Nath.jpg",
        bio: "Currently pursuing MBBS at Armed Forces Medical College, Pune",
        linkedin: "https://www.linkedin.com/in/sahul-nath-106154265",
      },
      {
        id: 88,
        name: "Sakshi Raj",
        designation: "Joined in 2020",
        imageUrl: "/images/team/alumni/Sakshi_Raj.jpg",
        bio: "Currently pursuing in B.Tech in Computer Science at Chandigarh Engineering College",
        linkedin: "https://www.linkedin.com/in/sakshi-raj-8724832a6/",
      },
      {
        id: 89,
        name: "Saloni Kumari",
        designation: "Joined in 2022",
        imageUrl: "/images/team/alumni/Saloni_Kumari.jpg",
        bio: "Currently pursuing B.Tech in Computer Science at BRCM College of Engineering and Technology ",
        linkedin: "https://www.linkedin.com/in/saloni-kumari-555909312?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: 90,
        name: "Sameer Kumar",
        designation: "Joined in 2021",
        imageUrl: "/images/team/alumni/Sameer_Kumar.jpeg",
        bio: "Currently pursuing B.Tech in Computer Science at National Institute of Technology, Patna",
        linkedin: "https://www.linkedin.com/in/sameer-kumar-75b0a8291",
      },
      {
        id: 91,
        name: "Samridh Shaurya Singh",
        designation: "Joined in 2022",
        imageUrl: "/images/team/alumni/Samridh_Shaurya_Singh.jpg",
        bio: "Currently pursuing B.Tech in Information Technology at Siddaganga Institute of Technology",
        linkedin: "http://www.linkedin.com/in/samridh-shaurya-singh-139063336",
      },
      {
        id: 92,
        name: "Saurav Ratan",
        designation: "Joined in 2023",
        imageUrl: "/images/team/alumni/Saurav_Ratan.jpg",
        bio: "Currently pursuing B.Tech in Computer Science at Indian Institute of Information Technology, Jabalpur",
      },
      {
        id: 93,
        name: "Seema Kumari",
        designation: "Joined in 2020",
        imageUrl: "/images/team/alumni/Seema_Kumari.jpg",
        bio: "Currently pursuing B.Tech in Information Technology at Chandigarh Engineering College",
        linkedin: "https://www.linkedin.com/in/seema-kumari-3011b5292",
      },
      {
        id: 94,
        name: "Seema Kumari",
        designation: "Joined in 2021",
        imageUrl: "/images/team/alumni/Seema_Kumari1.jpg",
        bio: "Currently pursuing B.Tech in Mechanical Engineering at National Institute of Technology, Agartala",
      },
      {
        id: 95,
        name: "Shalini Nath",
        designation: "Joined in 2021",
        imageUrl: "/images/team/alumni/Shalini_Nath.png",
        bio: "Currently pursuing B.Tech in Metallurgy at National Institute of Technology, Jameshedpur",
        linkedin: "https://www.linkedin.com/in/shalini-nath-a79a2b28b/",
      },
      {
        id: 96,
        name: "Shashi Kumar",
        designation: "Joined in 2022",
        imageUrl: "/images/team/alumni/Shashi_Kumar.jpg",
        bio: "Currently pursuing B.Tech in Mining Engineering at Indian Institute of Technology BHU",
        linkedin: "https://www.linkedin.com/in/shashi-kumar-1a85bb25b/",
      },
      {
        id: 97,
        name: "Sheetal Raj",
        designation: "Joined in 2021",
        imageUrl: "/images/team/alumni/Sheetal_Raj.jpg",
        bio: "Currently pursuing B.Tech in Computer Science and Business System at Techno Main Salt Lake",
        linkedin: "https://www.linkedin.com/in/sheetal-raj-964ab5271",
      },
      {
        id: 98,
        name: "Shilpa Kumari",
        designation: "Joined in 2021",
        imageUrl: "/images/team/alumni/Shilpa_Kumari.jpg",
        bio: "Currently pursuing B.Tech in Mining at Indian Institute of Technology, Kharagpur",
        linkedin: "https://www.linkedin.com/in/shilpa-kumari-0a0392236",
      },
      {
        id: 99,
        name: "Shobha Kumari",
        designation: "Joined in 2018",
        imageUrl: "/images/team/alumni/Shobha_Kumari.jpg",
        bio: "Currently pursuing Bachelor in Computer Applications at Mirza Ghalib College",
        
      },
      {
        id: 100,
        name: "Shravan Kumar",
        designation: "Joined in 2021",
        imageUrl: "/images/team/alumni/Shravan_Kumar.jpg",
        bio: "Currently pursuing B.Tech in Production Engineering at National Institute of Technology, Agartala",
      },
      {
        id: 101,
        name: "Shruti Kumari",
        designation: "Joined in 2022",
        imageUrl: "/images/team/alumni/Shruti_Kumari.JPG",
        bio: "Currently pursuing B.Tech in Computer Science at Netaji Subhash Engineering College",
        linkedin: "https://www.linkedin.com/in/shruti-kumari-618572323?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: 102,
        name: "Shruti Kumari",
        designation: "Joined in 2019",
        imageUrl: "/images/team/alumni/Shruti_Kumari1.jpg",
        bio: "Currently pursuing B.Tech in Computer Science with specialization in Data Science at Techno Main Salt Lake ",
        linkedin: "https://www.linkedin.com/in/shruti-kumari-925301254",
      },
      {
        id: 103,
        name: "Sneha Kumari",
        designation: "Joined in 2022",
        imageUrl: "/images/team/alumni/Sneha_Kumari.jpg",
        bio: "Currently pursuing B.Tech in Computer Science at BP Poddar Institute of Management and Technology ",
        linkedin: "https://www.linkedin.com/in/sneha-kumari-832836326?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: 104,
        name: "Sneha Kumari",
        designation: "Joined in 2021",
        imageUrl: "/images/team/alumni/Sneha_Kumari1.jpg",
        bio: "Currently pursuing B.Tech in Computer Science at Chandigarh Engineering College, Landran ",
        linkedin: "https://www.linkedin.com/in/sneha-kumari-09526a249/",
      },
      {
        id: 105,
        name: "Sonali Kumari",
        designation: "Joined in 2022",
        imageUrl: "/images/team/alumni/Sonali_Kumari.jpg",
        bio: "Currently pursuing B.Tech in Computer Science at BRCM College of Engineering and Technology ",
        linkedin: "https://www.linkedin.com/in/sonali-kumari-024182327?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: 106,
        name: "Sonu Kumar",
        designation: "Joined in 2021",
        imageUrl: "/images/team/alumni/Sonu_Kumar.jpg",
        bio: "Currently pursuing B.Tech and Integrated M.Tech Mathematics and Computing at Indian Institute of Technology, Dhanbad",
        linkedin: "https://www.linkedin.com/in/sonu-kumar-586315255",
      },
      {
        id: 107,
        name: "Sonu Raj",
        designation: "Joined in 2022",
        imageUrl: "/images/team/alumni/Sonu_Raj.jpg",
        bio: "Currently pursuing B.Tech in Computer Science at JB Institute of Technology",
        linkedin: "https://www.linkedin.com/in/sonu-r-b18a68331?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: 108,
        name: "Sujal Kumar",
        designation: "Joined in 2016",
        imageUrl: "/images/team/alumni/Sujal_Kumar.jpg",
        bio: "Currently pursuing B.Tech in Metallurgical and Materials Engineering at National Institute of Technology, Durgapur",
        linkedin: "https://www.linkedin.com/in/sujal-kumar-aab83525b",
      },
      {
        id: 109,
        name: "Sunny Kumar",
        designation: "Joined in 2023",
        imageUrl: "/images/team/alumni/Sunny_Kumar.JPG",
        bio: "Currently pursuing B.Tech in Electronics and Communication Engineering at Indian Institute of Information Technology , Design & Manufacturing",
        linkedin: "https://www.linkedin.com/in/sunny-kumar-455163290",
      },
      {
        id: 110,
        name: "Suraj Kumar",
        designation: "Joined in 2021",
        imageUrl: "/images/team/alumni/Suraj.jpg",
        bio: "Currently pursuing B.Tech in Mining Engineering at Indian Institute of Engineering Science and Technology ( IIEST ), Shibpur",
        linkedin: "https://www.linkedin.com/in/suraj-kumar-79b355326?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      },
      {
        id: 111,
        name: "Vijay Kumar",
        designation: "Joined in 2021",
        imageUrl: "/images/team/alumni/Vijay_Kumar.jpg",
        bio: "Currently pursuing B.Tech in Computer Science at Chandigarh Engineering College",
        linkedin: "https://www.linkedin.com/in/vijay-kumar-b20b52292",
      },
      {
        id: 112,
        name: "Vikash Kumar",
        designation: "Joined in 2020",
        imageUrl: "/images/team/alumni/Vikash_Kumar.jpg",
        bio: "Currently pursuing B.Tech in Computer Science with specialization in AI/ML at Techno Main Salt Lake",
        linkedin: "https://www.linkedin.com/in/vikashkumar78",
      },
  ];
  